# Generated by Django 5.1.4 on 2025-11-22 01:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('settore', models.CharField(help_text='Internal settore name from DB', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestockSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(choices=[('0', 'Off'), ('1', 'Early Morning'), ('2', 'Late Afternoon')], default='0', max_length=10)),
                ('tuesday', models.CharField(choices=[('0', 'Off'), ('1', 'Early Morning'), ('2', 'Late Afternoon')], default='0', max_length=10)),
                ('wednesday', models.CharField(choices=[('0', 'Off'), ('1', 'Early Morning'), ('2', 'Late Afternoon')], default='0', max_length=10)),
                ('thursday', models.CharField(choices=[('0', 'Off'), ('1', 'Early Morning'), ('2', 'Late Afternoon')], default='0', max_length=10)),
                ('friday', models.CharField(choices=[('0', 'Off'), ('1', 'Early Morning'), ('2', 'Late Afternoon')], default='0', max_length=10)),
                ('saturday', models.CharField(choices=[('0', 'Off'), ('1', 'Early Morning'), ('2', 'Late Afternoon')], default='0', max_length=10)),
                ('sunday', models.CharField(choices=[('0', 'Off'), ('1', 'Early Morning'), ('2', 'Late Afternoon')], default='0', max_length=10)),
                ('restock_time', models.TimeField(default='09:00', help_text='Time to run daily restock check')),
                ('restock_intervals', models.CharField(blank=True, editable=False, max_length=50)),
                ('base_coverage', models.DecimalField(decimal_places=1, default=4.5, help_text='Base coverage in days', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='supermarkets.storage')),
            ],
        ),
        migrations.CreateModel(
            name='RestockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_products', models.IntegerField(default=0)),
                ('products_ordered', models.IntegerField(default=0)),
                ('total_packages', models.IntegerField(default=0)),
                ('results', models.TextField(blank=True, help_text='JSON with detailed results')),
                ('error_message', models.TextField(blank=True)),
                ('coverage_used', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_logs', to='supermarkets.storage')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklists', to='supermarkets.storage')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('storage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supermarkets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='supermarkets.supermarket'),
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_var', models.SmallIntegerField(default=1)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='supermarkets.blacklist')),
            ],
            options={
                'ordering': ['product_code', 'product_var'],
                'unique_together': {('blacklist', 'product_code', 'product_var')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together={('supermarket', 'name')},
        ),
    ]
