# Generated by Django 5.1.4 on 2025-11-26 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='last_list_update',
            field=models.DateTimeField(blank=True, help_text='Last time product list was updated', null=True),
        ),
        migrations.CreateModel(
            name='ListUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_update_logs', to='supermarkets.storage')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ListUpdateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], default='biweekly', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='Enable automatic updates')),
                ('storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_update_schedule', to='supermarkets.storage')),
            ],
        ),
    ]
