# Generated by Django 5.1.4 on 2025-02-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='product_code',
        ),
    ]
