# Generated by Django 5.1.4 on 2025-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0002_remove_blacklist_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='product_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='product_var',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
