# Generated by Django 5.1.4 on 2025-02-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0003_blacklist_product_code_blacklist_product_var'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='product_var',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_var', models.SmallIntegerField()),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='supermarkets.blacklist')),
            ],
        ),
    ]
