# Generated by Django 5.1.4 on 2025-02-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0004_remove_blacklist_product_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistentry',
            options={'ordering': ['product_code']},
        ),
    ]
