# Generated by Django 5.1.4 on 2025-02-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0005_alter_blacklistentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockschedule',
            name='friday',
            field=models.CharField(choices=[('off', 'Off'), ('early', 'Early'), ('late', 'Late')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='restockschedule',
            name='monday',
            field=models.CharField(choices=[('off', 'Off'), ('early', 'Early'), ('late', 'Late')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='restockschedule',
            name='saturday',
            field=models.CharField(choices=[('off', 'Off'), ('early', 'Early'), ('late', 'Late')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='restockschedule',
            name='sunday',
            field=models.CharField(choices=[('off', 'Off'), ('early', 'Early'), ('late', 'Late')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='restockschedule',
            name='thursday',
            field=models.CharField(choices=[('off', 'Off'), ('early', 'Early'), ('late', 'Late')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='restockschedule',
            name='tuesday',
            field=models.CharField(choices=[('off', 'Off'), ('early', 'Early'), ('late', 'Late')], default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='restockschedule',
            name='wednesday',
            field=models.CharField(choices=[('off', 'Off'), ('early', 'Early'), ('late', 'Late')], default='off', max_length=10),
        ),
    ]
